#!/bin/bash

# Laravel Development Server Script
echo "Starting Laravel development server..."
echo "Server will be available at: http://0.0.0.0:8000"
echo "Press Ctrl+C to stop the server"
echo ""

# Run the Laravel development server
/Applications/XAMPP/xamppfiles/bin/php artisan serve --host=0.0.0.0 --port=8000

